baseURL = "http://example.org/"
languageCode = "es"
title = "🔥 Klaw | Kenshi"
theme = "ananke"
background_color_class = "bg-navy"

[params]
  #commentoEnable = true
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  discord = "Kenshi#123123"
  youtube = ""
  github = "https://github.com/klawx3"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "navy"
  featured_image = "/images/red_wall.png"
  body_classes = "avenir bg-near-white"
  recent_posts_number = 2